### ISSUE TITLE
set_openid_namespace

### ISSUE THREAD

**Issue by Arcanum417** [discourse/discourse-steam-login#11]
After clicking login using steam I get normal steam thing after clicking log in I get error 500 here is log dump.

```
Message

OpenID::InvalidOpenIDNamespace (Invalid null namespace: http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0)
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:198:in `set_openid_namespace'
Backtrace

/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:198:in `set_openid_namespace'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:161:in `block in _from_openid_args'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:151:in `each'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:151:in `_from_openid_args'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/message.rb:132:in `from_post_args'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/ruby-openid-2.7.0/lib/openid/consumer.rb:284:in `complete'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-openid-1.3.1/lib/rack/openid.rb:145:in `block in complete_authentication'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-openid-1.3.1/lib/rack/openid.rb:272:in `timeout_protection_from_identity_server'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-openid-1.3.1/lib/rack/openid.rb:143:in `complete_authentication'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-openid-1.3.1/lib/rack/openid.rb:95:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-openid-1.0.1/lib/omniauth/strategies/open_id.rb:87:in `openid_response'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-openid-1.0.1/lib/omniauth/strategies/open_id.rb:80:in `callback_phase'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:227:in `callback_call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:184:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/www/discourse/lib/middleware/anonymous_cache.rb:127:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/logster-1.2.5/lib/logster/middleware/reporter.rb:31:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
/var/www/discourse/config/initializers/100-quiet_logger.rb:13:in `call_with_quiet_assets'
/var/www/discourse/config/initializers/100-silence_logger.rb:26:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:278:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/message_bus-2.0.2/lib/message_bus/rack/middleware.rb:62:in `call'
/var/www/discourse/lib/middleware/request_tracker.rb:73:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:562:in `process_client'
/var/www/discourse/lib/scheduler/defer.rb:85:in `process_client'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'
/var/www/discourse/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.3.0/bin/unicorn:22:in `load'
/var/www/discourse/vendor/bundle/ruby/2.3.0/bin/unicorn:22:in `<main>'
Env

hostname	box-app
process_id	958
application_version	988aca6d92a64e05d5c2f04f139808ea93db8b56
HTTP_HOST	discourse.417rct.org
REQUEST_URI	/auth/steam/callback?_method=post&openid.ns=http%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0&openid.mode=id_res&openid.op_endpoint=https%253A%252F%252Fsteamcommunity.com%252Fopenid%252Flogin&openid.claimed_id=http%253A%252F%252Fsteamcommunity.com%252Fopenid%252Fid%252F76561198051483801&openid.identity=http%253A%252F%252Fsteamcommunity.com%252Fopenid%252Fid%252F76561198051483801&openid.return_to=http%253A%252F%252Fdiscourse.417rct.org%252Fauth%252Fsteam%252Fcallback%253F_method%253Dpost&openid.response_nonce=2016-11-27T03%253A33%253A19ZwkCSv6lE38kpQfmi6PMDG42tJoQ%253D&openid.assoc_handle=1234567890&openid.signed=signed%252Cop_endpoint%252Cclaimed_id%252Cidentity%252Creturn_to%252Cresponse_nonce%252Cassoc_handle&openid.sig=VobkwAP5Kio8%252Fog95tc1DYb29X8%253D
REQUEST_METHOD	GET
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_X_FORWARDED_FOR	195.168.89.37, 172.17.0.1
HTTP_X_REAL_IP	172.17.0.1
params	
_method	post
openid.ns	http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
openid.mode	id_res
openid.op_endpoint	https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin
openid.claimed_id	http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198051483801
openid.identity	http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198051483801
openid.return_to	http%3A%2F%2Fdiscourse.417rct.org%2Fauth%2Fsteam%2Fcallback%3F_method%3Dpost
openid.response_nonce	2016-11-27T03%3A33%3A19ZwkCSv6lE38kpQfmi6PMDG42tJoQ%3D
openid.assoc_handle	1234567890
openid.signed	signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle
openid.sig	VobkwAP5Kio8%2Fog95tc1DYb29X8%3D
```

**Comment by Arcanum417** [comment]
I now foud out it is some kind of issue with my apache proxy, any hints how to resolve this ?
